name: Build

on:
  push:
    branches: master

env:
  tag: v1.6.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        sudo apt install make git zlib1g-dev libssl-dev gperf php cmake g++
        mkdir artifacts
      
    - name: Fetch tdlib
      run: git clone --branch $tag --depth 1 https://github.com/tdlib/td.git td
      
    - name: Compile
      run: |
        rm -rf td/build
        mkdir td/build
        cd td/build
        CXXFLAGS="" cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../artifacts/current/ ..
        cmake --build . --target install
        
    - name: Cross-Compile for armhf
      run: |
        rm -rf td/build
        mkdir td/build
        cd td/build
        ARCH=arm CXXFLAGS="" CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ \
          cmake -DCMAKE_LINKER=/usr/arm-linux-gnueabihf/bin/ld -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=../../artifacts/armhf/ -DTD_ENABLE_LTO=ON -DCMAKE_CROSSCOMPILING=True \
                -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm \
                -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
                -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
                -DCMAKE_SHARED_LIBRARY_PREFIX=/usr/arm-linux-gnueabihf/ -DOPENSSL_ROOT_DIR=~/openssl-1.1.1g/ \
                -DOPENSSL_CRYPTO_LIBRARY=~/openssl-1.1.1g/crypto/libcrypto.so -DZLIB_LIBRARY=~/zlib-1.2.11/libz.so \
                -DOPENSSL_SSL_LIBRARY=~/openssl-1.1.1g/libssl.so ..
        cmake --build . --target install
        
    - uses: actions/upload-artifact@v2
      with:
        name: tdlib
        path: artifacts/
